name: home_services
description: home_services customer app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.1+20

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  # GET
  get: ^4.6.1
  get_storage: ^2.0.3
  # DIO
  dio: ^4.0.4
  dio_http_cache:
    git:
      url: https://github.com/vrtdev/dio-http-cache.git
      ref: feature/nullsafety-dio4
  # FONT
  auto_size_text: ^3.0.0
  #IMAGES, SLIDERS, LAYOUTS
  fialogs: ^2.0.3
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  flutter_svg: ^0.22.0
  flutter_staggered_grid_view: ^0.4.0
  image_picker: ^0.8.4+8
  cupertino_icons: ^1.0.4
  shimmer: ^2.0.0
  getwidget: ^2.0.4
  platform: ^3.1.0
  custom_radio_grouped_button: ^2.1.1


  # WEB
  webview_flutter: ^2.8.0
  flutter_html: ^2.1.5
  url_launcher: ^6.0.19
  # FIREBASE
  firebase_messaging: ^11.2.6
  cloud_firestore: ^3.1.8
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.7
  # GOOGLE MAPS
  google_maps_place_picker: ^2.1.0-nullsafety.3
  map_launcher: ^2.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^5.2.3
  sign_in_with_apple: ^3.3.0
  crypto: ^3.0.1
  flutter_facebook_auth: ^4.0.1
  flutter_signin_button: ^2.0.0
  restart_app: ^1.1.0
  animated_splash_screen: ^1.1.0
  lottie: ^1.2.1
  firebase_dynamic_links: ^4.0.8
  booking_calendar: ^1.0.1
  select_dialog: ^2.0.0
  google_fonts: ^2.3.1
  flutter_math_fork: ^0.3.3+1
  flutter_facebook_keyhash: ^0.0.4
  share_plus: ^3.1.0
  flutter_switch: ^0.3.2



dependency_overrides:
  flutter_svg: ^0.22.0
  flutter_math_fork: ^0.5.0
  provider: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  intl: ^0.17.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - config/
    - assets/img/
    - assets/icon/
    - assets/locales/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages